CREATE TABLE Member(
	IdM INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
	nama VARCHAR (50),
	alamat VARCHAR (100),
	email VARCHAR (50),
	wallet decimal(15,2)
);

CREATE TABLE Transaksi_kupon (
	IdTR INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
	waktu_transaksi DATE,
	IdM INT (6) UNSIGNED,
	CONSTRAINT FK_IdM
		FOREIGN KEY (IdM) REFERENCES Member(IdM)
);

CREATE TABLE kupon (
	IdK INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nominal decimal(15,2),
	kode_kupon VARCHAR (10)
);

CREATE TABLE Tkupon (
	IdTR INT (6) UNSIGNED,
	IdK INT (6) UNSIGNED,
	CONSTRAINT FK_IdTR
		FOREIGN KEY (IdTR) REFERENCES Transaksi_kupon(IdTR),
	CONSTRAINT FK_IdK
		FOREIGN KEY (IdK) REFERENCES kupon(IdK)
);


CREATE TABLE  enrollment (
	IdE INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	wktEnrollment DATE
);

CREATE TABLE enrollment_member (
	IdM INT (6) UNSIGNED,
	IdE INT (6) UNSIGNED,
	CONSTRAINT fkidm
		FOREIGN KEY (IdM) REFERENCES member(IdM),
	CONSTRAINT fkide
		FOREIGN KEY (IdE) REFERENCES enrollment(IdE)
);

CREATE TABLE pengajar (
	IdP INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nama VARCHAR (50),
	email VARCHAR (50)
);

CREATE TABLE course (
	IdC INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	batas_nilai INT (6),
	judulCourse VARCHAR (50),
	IdS INT (6),
	waktu_terbit_sertif DATE,
	IdP INT (6) UNSIGNED,
	CONSTRAINT fkidp
		FOREIGN KEY (IdP) REFERENCES pengajar(IdP)
);

CREATE TABLE nilai (
	IdN INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jumlah_nilai INT (6),
	IdC INT (6) UNSIGNED,
	CONSTRAINT fkidc
		FOREIGN KEY (IdC) REFERENCES course(IdC)
);

CREATE TABLE nilai_member (
	IdM INT (6) UNSIGNED,
	IdN INT (6) UNSIGNED,
	CONSTRAINT foreignkeyidm
		FOREIGN KEY (IdM) REFERENCES Member(IdM),
	CONSTRAINT foreignkeyidn
		FOREIGN KEY (IdN) REFERENCES nilai(IdN)
);


CREATE TABLE course_enrollment (
	IdE INT (6) UNSIGNED,
	IdC INT (6) UNSIGNED,
	CONSTRAINT foreignkeyide
		FOREIGN KEY (IdE) REFERENCES enrollment(IdE),
	CONSTRAINT foreignkeyidc
		FOREIGN KEY (IdC) REFERENCES course(IdC)
);

CREATE TABLE isi_course (
	IdC INT (6) UNSIGNED,
	CONSTRAINT fk_idc
		FOREIGN KEY (IdC) REFERENCES course(IdC),
	IdMod INT (6) UNSIGNED,
	id_ujian INT (6) UNSIGNED
);

CREATE TABLE admin (
	idA INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY 
);




